# from github
# - src: https://github.com/lujianmei/ansible-coreos-container-linux

# from galaxy
- src: deimosfr.coreos-container-linux
- src: deimosfr.coreos-ansible
- src: deimosfr.coreos-kubernetes
